### ISSUE TITLE
Abou the install problem

### ISSUE THREAD

**Issue by K-Alex13** [intel-analytics/bigdl-llm-tutorial#65] opened 2023-12-20 03:23 UTC
![1e78a760-4a92-41d4-97a2-9a71d357dcb2](https://github.com/intel-analytics/bigdl-llm-tutorial/assets/74948610/1c28f4fd-d26a-40b1-b6bb-c25c0c332dc6)
Not sure what is going wrong here, I did totally following the guild of bigdl.  Thank you very much for any response. 
Please help me.

**Comment by MeouSker77** [comment] 2023-12-20 05:36
Are you trying to use GPU and following this guide ? <https://bigdl.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html>

If yes, can you paste the output of this command (under cmd, not powershell) ? 
```
call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
```

**Comment by K-Alex13** [comment] 2023-12-20 06:12
> Are you trying to use GPU and following this guide ? https://bigdl.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html
> 
> If yes, can you paste the output of this command (under cmd, not powershell) ?
> 
> ```
> call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
> ```

![image](https://github.com/intel-analytics/bigdl-llm-tutorial/assets/74948610/01bca727-784f-439c-938e-9418eaac6930)
You mean this one here?

**Comment by MeouSker77** [comment] 2023-12-20 06:21
compiler, dnnl, mkl are necessary, seems like you didn't install dnnl ?

![image](https://github.com/intel-analytics/bigdl-llm-tutorial/assets/34214113/fca65fdd-ec3b-43f1-9013-78d212eb09e9)

**Comment by K-Alex13** [comment] 2023-12-20 06:24
Thank you for your response and how to install whant I need with conda env?

**Comment by MeouSker77** [comment] 2023-12-20 06:29
They are parts of [Intel® oneAPI Base Toolkit](https://www.intel.com/content/www/us/en/developer/tools/oneapi/base-toolkit-download.html) 2024.0.

When install oneapi 2024.0, you can install all components in it (this is default behavior).

**Comment by K-Alex13** [comment] 2023-12-20 06:30
I already install oneapi 2023.9  it is not working?

**Comment by MeouSker77** [comment] 2023-12-20 06:31
Now oneapi 2023.x is not supported on Windows, only oneapi 2024.0 is supported

**Comment by K-Alex13** [comment] 2023-12-20 07:02
Thank you for your help, I am update the oneapi version now.

**Comment by jason-dai** [comment] 2023-12-20 07:20
See GPU installation guide https://bigdl.readthedocs.io/en/latest/doc/LLM/Overview/install_gpu.html

**Comment by K-Alex13** [comment] 2023-12-20 07:53
![image](https://github.com/intel-analytics/bigdl-llm-tutorial/assets/74948610/8fa50630-097c-48ac-aefc-82a13251ec2b)
I change the version of oneapi, and still have the same errors.   I do not know what is wirong here.  The picture is the new call results.

**Comment by K-Alex13** [comment] 2023-12-20 08:02
This problem is solved right now, thank you very much

**Comment by hkvision** [comment] 2023-12-21 02:08
Since the issue is resolved, closing this issue. Feel free to reopen it or open a new one if you have future issues :)

**Closed** 2023-12-21 02:18 UTC
